### ISSUE TITLE
Simple read/write workload

### ISSUE THREAD

**Issue by tomkins** [tomkins/wagtail-sqlite-benchmark#3]
Have an editor user updating pages whilst other users are viewing pages.

**Comment by tomkins** [comment]
Gunicorn, 8 workers, 8 users:

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /[base.HomePage]                                                                 939     0(0.00%) |     35      28     368     32 |   15.74        0.00
GET      /[breads.BreadPage]                                                            10195     0(0.00%) |     19      13     110     17 |  170.87        0.00
GET      /[breads.BreadsIndexPage]                                                        900     0(0.00%) |     32      25     193     29 |   15.08        0.00
GET      /[locations.LocationPage]                                                       5413     0(0.00%) |     20      15     103     18 |   90.72        0.00
GET      /[locations.LocationsIndexPage]                                                  920     0(0.00%) |     22      16     235     20 |   15.42        0.00
GET      /admin/                                                                            8     0(0.00%) |     56       6     213      9 |    0.13        0.00
GET      /admin/api/main/pages/                                                             8     0(0.00%) |     43      33      55     39 |    0.13        0.00
POST     /admin/login/?next=/admin/                                                         8     0(0.00%) |    176     105     412    110 |    0.13        0.00
GET      /admin/logout/                                                                     7     0(0.00%) |     36      10     177     13 |    0.12        0.00
GET      /admin/pages/[base.HomePage]/edit/                                                16     0(0.00%) |     55      51      88     54 |    0.27        0.00
POST     /admin/pages/[base.HomePage]/edit/                                                16     0(0.00%) |     80      76      84     80 |    0.27        0.00
GET      /admin/pages/[breads.BreadPage]/edit/                                            198     0(0.00%) |     48      42     114     46 |    3.32        0.00
POST     /admin/pages/[breads.BreadPage]/edit/                                            197     0(0.00%) |    108      92     286    100 |    3.30        0.00
GET      /admin/pages/[breads.BreadsIndexPage]/edit/                                       22     0(0.00%) |     42      36      95     38 |    0.37        0.00
POST     /admin/pages/[breads.BreadsIndexPage]/edit/                                       22     0(0.00%) |     93      86     146     91 |    0.37        0.00
GET      /admin/pages/[locations.LocationPage]/edit/                                      106     0(0.00%) |     69      59     266     63 |    1.78        0.00
POST     /admin/pages/[locations.LocationPage]/edit/                                      106     1(0.94%) |    110      50     177    110 |    1.78        0.02
GET      /admin/pages/[locations.LocationsIndexPage]/edit/                                 18     0(0.00%) |     39      36      63     38 |    0.30        0.00
POST     /admin/pages/[locations.LocationsIndexPage]/edit/                                 18     0(0.00%) |     94      78     150     90 |    0.30        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                     19117     1(0.01%) |     23       6     412     18 |  320.41        0.02

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /[base.HomePage]                                                                       32     35     37     39     43     48     55     72    370    370    370    939
GET      /[breads.BreadPage]                                                                    17     18     19     20     23     25     30     59     90    110    110  10195
GET      /[breads.BreadsIndexPage]                                                              29     31     34     35     39     42     50     74    190    190    190    900
GET      /[locations.LocationPage]                                                              18     19     21     21     24     26     31     53     92    100    100   5413
GET      /[locations.LocationsIndexPage]                                                        20     21     23     24     26     30     37     59    240    240    240    920
GET      /admin/                                                                                14     17    180    180    210    210    210    210    210    210    210      8
GET      /admin/api/main/pages/                                                                 42     51     53     53     55     55     55     55     55     55     55      8
POST     /admin/login/?next=/admin/                                                            120    150    290    290    410    410    410    410    410    410    410      8
GET      /admin/logout/                                                                         13     13     15     15    180    180    180    180    180    180    180      7
GET      /admin/pages/[base.HomePage]/edit/                                                     54     55     55     55     55     88     88     88     88     88     88     16
POST     /admin/pages/[base.HomePage]/edit/                                                     81     82     83     83     84     85     85     85     85     85     85     16
GET      /admin/pages/[breads.BreadPage]/edit/                                                  46     46     47     47     52     64     84    110    110    110    110    198
POST     /admin/pages/[breads.BreadPage]/edit/                                                 100    110    110    110    120    130    180    220    290    290    290    197
GET      /admin/pages/[breads.BreadsIndexPage]/edit/                                            38     39     40     40     41     72     95     95     95     95     95     22
POST     /admin/pages/[breads.BreadsIndexPage]/edit/                                            91     93     94     94     95     96    150    150    150    150    150     22
GET      /admin/pages/[locations.LocationPage]/edit/                                            63     64     64     66     86     91    130    140    270    270    270    106
POST     /admin/pages/[locations.LocationPage]/edit/                                           110    110    110    110    120    150    160    170    180    180    180    106
GET      /admin/pages/[locations.LocationsIndexPage]/edit/                                      38     38     39     39     41     63     63     63     63     63     63     18
POST     /admin/pages/[locations.LocationsIndexPage]/edit/                                      91     92     94     96    110    150    150    150    150    150    150     18
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                             18     20     22     24     32     45     90    100    150    370    410  19117

Error report
# occurrences      Error
------------------|---------------------------------------------------------------------------------------------------------------------------------------------
1                  POST /admin/pages/[locations.LocationPage]/edit/: HTTPError('500 Server Error: Internal Server Error for url: /admin/pages/[locations.LocationPage]/edit/')
------------------|---------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by tomkins** [comment]
Slightly surprised at seeing an error with just 1 editor:

```
Internal Server Error: /admin/pages/65/edit/
Traceback (most recent call last):
  File "/Users/tomkins/.virtualenvs/bakerydemo/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tomkins/.virtualenvs/bakerydemo/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked
```

Time to activate the WAL.

**Comment by tomkins** [comment]
After adding WAL:

```
Type     Name                                                                          # reqs      # fails |    Avg     Min     Max    Med |   req/s  failures/s
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /[base.HomePage]                                                                1184     0(0.00%) |     30      25     335     29 |   19.84        0.00
GET      /[breads.BreadPage]                                                            11980     0(0.00%) |     15      11     222     15 |  200.74        0.00
GET      /[breads.BreadsIndexPage]                                                       1074     0(0.00%) |     28      22     190     26 |   18.00        0.00
GET      /[locations.LocationPage]                                                       6445     0(0.00%) |     17      13     109     16 |  108.00        0.00
GET      /[locations.LocationsIndexPage]                                                 1079     0(0.00%) |     19      14     221     18 |   18.08        0.00
GET      /admin/                                                                            8     0(0.00%) |     48       5     176      7 |    0.13        0.00
GET      /admin/api/main/pages/                                                             8     0(0.00%) |     54      30     185     35 |    0.13        0.00
POST     /admin/login/?next=/admin/                                                         8     0(0.00%) |    144      96     410    100 |    0.13        0.00
GET      /admin/logout/                                                                     7     0(0.00%) |     12       8      19     13 |    0.12        0.00
GET      /admin/pages/[base.HomePage]/edit/                                                17     0(0.00%) |     55      48     104     52 |    0.28        0.00
POST     /admin/pages/[base.HomePage]/edit/                                                17     0(0.00%) |     70      63     110     66 |    0.28        0.00
GET      /admin/pages/[breads.BreadPage]/edit/                                            224     0(0.00%) |     46      40     277     43 |    3.75        0.00
POST     /admin/pages/[breads.BreadPage]/edit/                                            223     1(0.45%) |     94      16     193     90 |    3.74        0.02
GET      /admin/pages/[breads.BreadsIndexPage]/edit/                                       24     0(0.00%) |     35      33      40     35 |    0.40        0.00
POST     /admin/pages/[breads.BreadsIndexPage]/edit/                                       24     0(0.00%) |     77      73      86     77 |    0.40        0.00
GET      /admin/pages/[locations.LocationPage]/edit/                                      121     0(0.00%) |     64      58     133     60 |    2.03        0.00
POST     /admin/pages/[locations.LocationPage]/edit/                                      121     1(0.83%) |     96      42     278     93 |    2.03        0.02
GET      /admin/pages/[locations.LocationsIndexPage]/edit/                                 13     0(0.00%) |     37      32      57     35 |    0.22        0.00
POST     /admin/pages/[locations.LocationsIndexPage]/edit/                                 13     0(0.00%) |     83      69     171     78 |    0.22        0.00
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
         Aggregated                                                                     22590     2(0.01%) |     19       5     410     16 |  378.53        0.03

Response time percentiles (approximated)
Type     Name                                                                                  50%    66%    75%    80%    90%    95%    98%    99%  99.9% 99.99%   100% # reqs
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
GET      /[base.HomePage]                                                                       29     29     30     30     32     34     45     95    110    340    340   1184
GET      /[breads.BreadPage]                                                                    15     15     16     16     17     18     21     26    100    110    220  11980
GET      /[breads.BreadsIndexPage]                                                              26     27     27     27     29     32     58     92    120    190    190   1074
GET      /[locations.LocationPage]                                                              16     17     17     17     18     20     23     32    100    110    110   6445
GET      /[locations.LocationsIndexPage]                                                        18     18     19     19     20     22     26     32    190    220    220   1079
GET      /admin/                                                                                10     10    170    170    180    180    180    180    180    180    180      8
GET      /admin/api/main/pages/                                                                 35     38     42     42    190    190    190    190    190    190    190      8
POST     /admin/login/?next=/admin/                                                            110    110    130    130    410    410    410    410    410    410    410      8
GET      /admin/logout/                                                                         13     14     15     15     19     19     19     19     19     19     19      7
GET      /admin/pages/[base.HomePage]/edit/                                                     52     52     54     54     60    100    100    100    100    100    100     17
POST     /admin/pages/[base.HomePage]/edit/                                                     66     68     68     70     92    110    110    110    110    110    110     17
GET      /admin/pages/[breads.BreadPage]/edit/                                                  43     44     44     45     49     66    100    110    280    280    280    224
POST     /admin/pages/[breads.BreadPage]/edit/                                                  90     91     93     94    100    130    170    180    190    190    190    223
GET      /admin/pages/[breads.BreadsIndexPage]/edit/                                            35     35     36     36     37     37     40     40     40     40     40     24
POST     /admin/pages/[breads.BreadsIndexPage]/edit/                                            77     77     79     80     84     84     87     87     87     87     87     24
GET      /admin/pages/[locations.LocationPage]/edit/                                            60     61     62     63     68     88    100    130    130    130    130    121
POST     /admin/pages/[locations.LocationPage]/edit/                                            93     94     95     96     98    100    160    170    280    280    280    121
GET      /admin/pages/[locations.LocationsIndexPage]/edit/                                      35     37     37     37     46     57     57     57     57     57     57     13
POST     /admin/pages/[locations.LocationsIndexPage]/edit/                                      78     78     78     79     80    170    170    170    170    170    170     13
--------|--------------------------------------------------------------------------------|--------|------|------|------|------|------|------|------|------|------|------|------
         Aggregated                                                                             16     17     18     18     28     32     88     93    150    280    410  22590

Error report
# occurrences      Error
------------------|---------------------------------------------------------------------------------------------------------------------------------------------
1                  POST /admin/pages/[breads.BreadPage]/edit/: HTTPError('500 Server Error: Internal Server Error for url: /admin/pages/[breads.BreadPage]/edit/')
1                  POST /admin/pages/[locations.LocationPage]/edit/: HTTPError('500 Server Error: Internal Server Error for url: /admin/pages/[locations.LocationPage]/edit/')
------------------|---------------------------------------------------------------------------------------------------------------------------------------------
```

Improved performance - but still getting a few "database is locked" errors.
